using another way to run other scenes in ci

diff --git a/.github/workflows/launch.yml b/.github/workflows/launch.yml
--- a/.github/workflows/launch.yml
+++ b/.github/workflows/launch.yml
@@ -14,34 +14,41 @@ jobs:
         steps:
         - uses: actions/checkout@v2
         - name: Install Xvfb
-          run: dnf install xorg-x11-server-Xvfb psmisc xdotool -y
-        - name: Build
-          shell: bash
-          run: "make 2>&1 | tee build_output"
-        - name: Run
+          run: dnf install xorg-x11-server-Xvfb psmisc -y
+        - name: Run default scene
           shell: bash
           run: |
-            echo "game not started">ci_state
+            make 2>&1 | tee build_output
+            echo "default scene: game not started">>ci_state
             Xvfb :1 -screen 0 1024x768x24 &
             export DISPLAY="1:0"
-            export EPIDEBUG=1
-            export DEBUG=1
-            sh -c "
-              sleep 4
-              && WID=$(xdotool search --classname "my_rpg")
-              && xdotool windowmove --window $WID 0 0
-              && sleep 1
-              && echo 'Clicking on the play button'
-              && xdotool mousemove --window $WID 960 270 # click play button
-              && xdotool click --window $WID 1
-            " &
-            sh -c "sleep 20 && killall my_rpg" &
-            bash -c './my_rpg; CODE=$?; if [[ $CODE == 143 ]]; then echo "success: ran for 20 seconds without crash">ci_state; exit 0; else echo "failure: exited with code $CODE">ci_state; exit $CODE; fi'
+            sh -c "sleep 5 && killall my_rpg" &
+            bash -c './my_rpg; CODE=$?; if [[ $CODE == 143 ]]; then echo "default scene: success: ran for 20 seconds without crash">>ci_state; exit 0; else echo "failure: exited with code $CODE">ci_state; exit $CODE; fi'
+        - name: Run menu scene
+          shell: bash
+          run: |
+            sed -i 's/set_pending_scene.game.*/set_pending_scene(game, MENU_SCENE);/g' src/game.c
+            make 2>&1 | tee -a build_output"
+            echo "menu scene: game not started">>ci_state
+            Xvfb :1 -screen 0 1024x768x24 &
+            export DISPLAY="1:0"
+            sh -c "sleep 5 && killall my_rpg" &
+            bash -c './my_rpg; CODE=$?; if [[ $CODE == 143 ]]; then echo "menu scene: success: ran for 20 seconds without crash">>ci_state; exit 0; else echo "failure: exited with code $CODE">ci_state; exit $CODE; fi'
+        - name: Run play scene
+          shell: bash
+          run: |
+            sed -i 's/set_pending_scene.game.*/set_pending_scene(game, PLAY_SCENE);/g' src/game.c
+            make 2>&1 | tee -a build_output"
+            echo "play scene: game not started">>ci_state
+            Xvfb :1 -screen 0 1024x768x24 &
+            export DISPLAY="1:0"
+            sh -c "sleep 10 && killall my_rpg" &
+            bash -c './my_rpg; CODE=$?; if [[ $CODE == 143 ]]; then echo "play scene: success: ran for 20 seconds without crash">>ci_state; exit 0; else echo "failure: exited with code $CODE">ci_state; exit $CODE; fi'
         - name: Send notification
           shell: bash
           if: ${{ github.event_name == 'push' && always() }}
           run: |
             checkout=$(git log -1 --pretty=format:"*Checkout:%d: %h %s*")
             state=$(cat ci_state)
-            echo '{"content": "**'$GITHUB_REPOSITORY'**\n'$checkout'\nAttempting to launch game: `'$state'`"}' > notification_data
+            echo '{"content": "**'$GITHUB_REPOSITORY'**\n'$checkout'\nAttempting to launch game: ```\n'$state'\n```"}' > notification_data
             curl --data "$(cat notification_data)" --header "Content-Type: application/json" https://discord.com/api/webhooks/823450813899866143/BBDxIXReQq8zMX6DTtCWL9bTrXZC_zamaAoLZ4zH7pETRi5T9loJSWozYeK1NfaCZFtE
